import {
  Activity,
  Bell,
  ChevronRight,
  Cloud,
  Copy,
  Database,
  Download,
  FileText,
  Folder,
  FolderOpen,
  HelpCircle,
  LayoutGrid,
  Lock,
  Menu,
  MoreVertical,
  PlusCircle,
  RefreshCw,
  Search,
  Settings,
  Share,
  ShieldAlert,
  ShieldCheck,
  Terminal,
  Trash2,
  Upload,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the Material Symbols glyph names used in the mock UI
 * (docs/stitch_secure_s3_desktop_explorer) to lucide-react icons.
 * Use lucide directly in new code; this map exists to preserve the
 * design language while standardizing on a tree-shakeable icon set.
 */
export const iconMap = {
  account_tree: LayoutGrid,
  add: PlusCircle,
  analytics: Activity,
  cloud: Cloud,
  cloud_queue: Cloud,
  content_copy: Copy,
  database: Database,
  delete: Trash2,
  description: FileText,
  download: Download,
  enhanced_encryption: ShieldCheck,
  encrypted: Lock,
  expand_more: ChevronRight,
  folder: Folder,
  folder_open: FolderOpen,
  help: HelpCircle,
  lock: Lock,
  menu: Menu,
  more_vert: MoreVertical,
  notifications: Bell,
  person: User,
  search: Search,
  settings: Settings,
  share: Share,
  shield: ShieldCheck,
  admin_panel_settings: ShieldCheck,
  sync: RefreshCw,
  terminal: Terminal,
  upload: Upload,
  users: Users,
  verified_user: ShieldCheck,
  warning: ShieldAlert,
  close: X,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;
